=== james-shijiachen/FastLCDP/src/main/resources/database-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- 根元素：database -->
    <xs:element name="database" type="DatabaseType"/>

    <!-- 数据库类型定义 -->
    <xs:complexType name="DatabaseType">
        <xs:sequence>
            <xs:element name="tables" type="TablesType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="version" type="xs:string" use="optional"/>
        <xs:attribute name="charset" type="CharsetType" use="optional"/>
        <xs:attribute name="collation" type="CollationType" use="optional"/>
        <xs:attribute name="engine" type="EngineType" use="optional"/>
        <xs:attribute name="comment" type="xs:string" use="optional"/>
    </xs:complexType>

    <!-- 表集合类型定义 -->
    <xs:complexType name="TablesType">
        <xs:sequence>
            <xs:element name="table" type="TableType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 表类型定义 -->
    <xs:complexType name="TableType">
        <xs:sequence>
            <xs:element name="fields" type="FieldsType" minOccurs="0"/>
            <xs:element name="indexes" type="IndexesType" minOccurs="0"/>
            <xs:element name="relations" type="RelationsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="TableTypeEnum" use="optional" default="ENTITY"/>
        <xs:attribute name="comment" type="xs:string" use="optional"/>
        <xs:attribute name="extends" type="xs:string" use="optional"/>
        <xs:attribute name="engine" type="EngineType" use="optional"/>
        <xs:attribute name="charset" type="CharsetType" use="optional"/>
        <xs:attribute name="collation" type="CollationType" use="optional"/>
    </xs:complexType>

    <!-- 字段集合类型定义 -->
    <xs:complexType name="FieldsType">
        <xs:sequence>
            <xs:element name="field" type="FieldType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 字段类型定义 -->
    <xs:complexType name="FieldType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="DataType" use="required"/>
        <xs:attribute name="length" type="xs:positiveInteger" use="optional"/>
        <xs:attribute name="precision" type="xs:positiveInteger" use="optional"/>
        <xs:attribute name="scale" type="xs:nonNegativeInteger" use="optional"/>
        <xs:attribute name="nullable" type="xs:boolean" use="optional" default="true"/>
        <xs:attribute name="primaryKey" type="PrimaryKeyType" use="optional" default="NONE"/>
        <xs:attribute name="autoIncrement" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="unique" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="defaultValue" type="xs:string" use="optional"/>
        <xs:attribute name="comment" type="xs:string" use="optional"/>
    </xs:complexType>

    <!-- 数据类型枚举 -->
    <xs:simpleType name="DataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="LONG"/>
            <xs:enumeration value="DECIMAL"/>
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="CHAR"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="TEXT"/>
            <xs:enumeration value="BLOB"/>
            <xs:enumeration value="DATETIME"/>
            <xs:enumeration value="JSON"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 字符集类型枚举 -->
    <xs:simpleType name="CharsetType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="utf8"/>
            <xs:enumeration value="utf8mb4"/>
            <xs:enumeration value="latin1"/>
            <xs:enumeration value="gbk"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 排序规则类型枚举 -->
    <xs:simpleType name="CollationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="utf8_general_ci"/>
            <xs:enumeration value="utf8mb4_general_ci"/>
            <xs:enumeration value="latin1_swedish_ci"/>
            <xs:enumeration value="gbk_chinese_ci"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 存储引擎类型枚举 -->
    <xs:simpleType name="EngineType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="InnoDB"/>
            <xs:enumeration value="MyISAM"/>
            <xs:enumeration value="Memory"/>
            <xs:enumeration value="Archive"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 表类型枚举 -->
    <xs:simpleType name="TableTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ABSTRACT"/>
            <xs:enumeration value="ENTITY"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 主键类型枚举 -->
    <xs:simpleType name="PrimaryKeyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SINGLE"/>
            <xs:enumeration value="COMPOSITE"/>
            <xs:enumeration value="AUTO_INCREMENT"/>
            <xs:enumeration value="UUID"/>
            <xs:enumeration value="SEQUENCE"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 索引集合类型定义 -->
    <xs:complexType name="IndexesType">
        <xs:sequence>
            <xs:element name="index" type="IndexType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 索引类型定义 -->
    <xs:complexType name="IndexType">
        <xs:sequence>
            <xs:element name="columns" type="IndexColumnsType"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="IndexTypeEnum" use="optional" default="NORMAL"/>
        <xs:attribute name="comment" type="xs:string" use="optional"/>
    </xs:complexType>

    <!-- 索引类型枚举 -->
    <xs:simpleType name="IndexTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRIMARY"/>
            <xs:enumeration value="UNIQUE"/>
            <xs:enumeration value="NORMAL"/>
            <xs:enumeration value="FULLTEXT"/>
            <xs:enumeration value="SPATIAL"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 索引列集合类型定义 -->
    <xs:complexType name="IndexColumnsType">
        <xs:sequence>
            <xs:element name="column" type="IndexColumnType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 索引列类型定义 -->
    <xs:complexType name="IndexColumnType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="order" type="SortOrder" use="optional" default="ASC"/>
        <xs:attribute name="length" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <!-- 排序顺序枚举 -->
    <xs:simpleType name="SortOrder">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ASC"/>
            <xs:enumeration value="DESC"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- 关系集合类型定义 -->
    <xs:complexType name="RelationsType">
        <xs:sequence>
            <xs:element name="relation" type="RelationType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 关系类型定义 -->
    <xs:complexType name="RelationType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="column" type="xs:string" use="required"/>
        <xs:attribute name="referenceTable" type="xs:string" use="required"/>
        <xs:attribute name="referenceColumn" type="xs:string" use="required"/>
        <xs:attribute name="onDelete" type="ReferentialAction" use="optional" default="RESTRICT"/>
        <xs:attribute name="onUpdate" type="ReferentialAction" use="optional" default="RESTRICT"/>
        <xs:attribute name="comment" type="xs:string" use="optional"/>
    </xs:complexType>

    <!-- 引用动作枚举 -->
    <xs:simpleType name="ReferentialAction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RESTRICT"/>
            <xs:enumeration value="CASCADE"/>
            <xs:enumeration value="SET NULL"/>
            <xs:enumeration value="NO ACTION"/>
            <xs:enumeration value="SET DEFAULT"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== james-shijiachen/FastLCDP/examples/simple-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<database name="simple_db" version="1.0" comment="简单示例数据库"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../src/main/resources/database-schema.xsd">
    <tables>
        <!-- 用户表 -->
        <table name="user" comment="用户表">
            <fields>
                <field name="id" type="LONG" primaryKey="true" autoIncrement="true" comment="用户ID"/>
                <field name="username" type="STRING" length="50" nullable="false" unique="true" comment="用户名"/>
                <field name="email" type="STRING" length="100" nullable="false" unique="true" comment="邮箱"/>
                <field name="password" type="STRING" length="255" nullable="false" comment="密码"/>
                <field name="age" type="INTEGER" comment="年龄"/>
                <field name="balance" type="DECIMAL" precision="10" scale="2" defaultValue="0.00" comment="余额"/>
                <field name="is_active" type="BOOLEAN" nullable="false" defaultValue="true" comment="是否激活"/>
                <field name="created_at" type="DATETIME" defaultValue="CURRENT_TIMESTAMP" comment="创建时间"/>
            </fields>
            <indexes>
                <index name="uk_username" type="UNIQUE">
                    <columns>
                        <column name="username"/>
                    </columns>
                </index>
                <index name="idx_email" type="NORMAL">
                    <columns>
                        <column name="email"/>
                    </columns>
                </index>
            </indexes>
        </table>
        
        <!-- 订单表 -->
        <table name="order" comment="订单表">
            <fields>
                <field name="id" type="LONG" primaryKey="true" autoIncrement="true" comment="订单ID"/>
                <field name="order_no" type="STRING" length="32" nullable="false" unique="true" comment="订单号"/>
                <field name="user_id" type="LONG" nullable="false" comment="用户ID"/>
                <field name="total_amount" type="DECIMAL" precision="10" scale="2" nullable="false" comment="总金额"/>
                <field name="status" type="STRING" length="20" nullable="false" defaultValue="pending" comment="订单状态"/>
                <field name="created_at" type="DATETIME" defaultValue="CURRENT_TIMESTAMP" comment="创建时间"/>
                <field name="updated_at" type="DATETIME" defaultValue="CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" comment="更新时间"/>
            </fields>
            <indexes>
                <index name="uk_order_no" type="UNIQUE">
                    <columns>
                        <column name="order_no"/>
                    </columns>
                </index>
                <index name="idx_user_id" type="NORMAL">
                    <columns>
                        <column name="user_id"/>
                    </columns>
                </index>
                <index name="idx_status_created" type="NORMAL">
                    <columns>
                        <column name="status"/>
                        <column name="created_at" order="DESC"/>
                    </columns>
                </index>
            </indexes>
            <relations>
                <relation name="fk_order_user" column="user_id" referenceTable="user" referenceColumn="id" onDelete="RESTRICT" onUpdate="CASCADE"/>
            </relations>
        </table>
    </tables>
</database>
